//AUTOGENERATED FILE FROM png2mtspr
#define toadbody_TILE_H 8
#define toadbody_WIDTH 16
#define toadbody_HEIGHT 24
#define toadbody_PIVOT_X 8
#define toadbody_PIVOT_Y 12

extern const UINT8 toadbody_data[240];
extern const metasprite_t* const toadbody_metasprites[4];
