//AUTOGENERATED FILE FROM png2mtspr
#define toadsmoke_TILE_H 8
#define toadsmoke_WIDTH 8
#define toadsmoke_HEIGHT 16
#define toadsmoke_PIVOT_X 4
#define toadsmoke_PIVOT_Y 8

extern const UINT8 toadsmoke_data[112];
extern const metasprite_t* const toadsmoke_metasprites[4];
